apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: show-req-header
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube
    repoURL: https://github.com/onurbolatogluu/show-req-header.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
