apiVersion: v1
kind: Service
metadata:
  name: show-req-header-service
spec:
  selector:
    app: show-req-header
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
