name: Docker Build & Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: onurbolatogluu/show-req-header:${{ github.sha }}

      - name: Print pod file
        run: |
          cat kube/show-req-header-pod.yml

      - name: Update image tag
        run: |
          awk -v sha=${{ github.sha }} '/image:/ {sub(/:.*/,"", $2); print $1 " " $2 ":" sha; next} 1' kube/show-req-header-pod.yml > tmp && mv tmp kube/show-req-header-pod.yml

      - name: Print pod file2
        run: |
          cat kube/show-req-header-pod.yml

